//
// Created by XZBbb on 2023/12/31.
//

#ifndef C_STATISTICSOFFREEBEDINACOLLEGE_H
#define C_STATISTICSOFFREEBEDINACOLLEGE_H
void StatisticsOfFreeBedInACollege();
#endif //C_STATISTICSOFFREEBEDINACOLLEGE_H
